### PR TITLE
WID-123, WID-124, WID-126: Add file operations

### PR DESCRIPTION
**Pull request by davidbacter01**
Adds new functionality:
- Adds contextual menu for file operations;
- Download files to drive with drag & drop;
- Download files to drive from button in contextual menu;
- Download files to local from contextual menu;
- Upload files from drive to bucket with drag & drop;
- Upload files from local to bucket with drag & drop;
- Delete files in bucket from contextual menu;
- Rename files in bucket from contextual menu.

### CODE REVIEW

**Comment by liadomide** [comment]
A very generic point: Maybe GitHub actions could be improved on this module ?
For example, coverage only appears in the logs of a build, and you will need to expand the logs for step `name: Build the extension` to see the resulting coverage - almost as good as inexistent, because nobody will dig that deep to check.
Perhaps we should integrate a coverage specific action to have cov % visible directly on a commit action ?

**Comment by davidbacter01** [comment]
@liadomide would this (https://github.com/the-virtual-brain/tvb-ext-bucket/commit/1c5aac4b9998324c39bb344be388650792317034#annotation_8726977585) be enough or is there something else that you have in mind?

**Comment by davidbacter01** [comment]
@popaula937 these are good observations. The drag and drop drive-download functionality is implemented and should be working. I will address the other points in a future commit. Thank for the recommendations!

**Comment by popaula937** [comment]
Hm, you are right, but it somehow does not always work for me. I am testing this a little further.

**Comment by liadomide** [comment]
> @liadomide would this ([1c5aac4#annotation_8726977585](https://github.com/the-virtual-brain/tvb-ext-bucket/commit/1c5aac4b9998324c39bb344be388650792317034#annotation_8726977585)) be enough or is there something else that you have in mind?

`jestcoverage` seems nice, it brings an inline report - immediate to see.
The disadvantage of it could be that for every commit a new comment on the PR appears (with the new report), and you either manually hide these, or you have a long history .... it might become cumbersome to see comments from people on the PR. Also, I do not see the coverage details (like what files, what lines are covered).

I was having in mind something like here on tvb-gdist (Cython, C++ and Python code - but the plugin should be generic):
image

**Pull request merged**
